{{- range $appName, $app := .Values.kubernetes.apps }}
{{- $ctx := dict "app" $app "appName" $appName "root" $ }}
{{- if and $app.secret $app.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $app.secret.name | default (include "k8s-app.fullname" $ctx) }}
  namespace: {{ include "k8s-app.namespace" $ }}
  labels:
    {{- include "k8s-app.labels" $ctx | nindent 4 }}
    {{- with $app.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    {{- with $app.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ $app.secret.type }}
{{- with $app.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $app.secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }} 