{{- range $appName, $app := .Values.kubernetes.apps }}
{{- $ctx := dict "app" $app "appName" $appName "root" $ }}
{{- if and $app.service $app.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-app.fullname" $ctx }}
  namespace: {{ include "k8s-app.namespace" $ }}
  labels:
    {{- include "k8s-app.labels" $ctx | nindent 4 }}
    {{- with $app.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- with $app.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $app.service.type }}
  ports:
    - port: {{ $app.service.port }}
      targetPort: {{ $app.service.targetPort }}
      protocol: TCP
      name: http
      {{- with $app.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  selector:
    {{- include "k8s-app.selectorLabels" $ctx | nindent 4 }}
{{- end }}
{{- end }} 