{{- range .Values.kubernetes.apps }}
{{- $app := . }}
{{- $ctx := dict "app" $app "root" $ }}
{{- if and $app.virtualService $app.virtualService.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $app.virtualService.name | default (include "k8s-app.fullname" $ctx) }}
  namespace: {{ include "k8s-app.namespace" $ }}
  labels:
    {{- include "k8s-app.labels" $ctx | nindent 4 }}
    {{- with $app.virtualService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    {{- with $app.virtualService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $app.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $app.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $app.virtualService.http }}
  http:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }} 